language: c
git:
  submodules: false

env: B=autotools

os: linux

cache:
  apt: true

install:
  - curl -4 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04 ./" | sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      autoconf-archive
      bison
      docbook-xsl
      flex
      gradle-2.2.1
      libcap-dev
      libdbd-sqlite3
      libdbi0-dev
      libesmtp-dev
      libevtlog-dev
      libgeoip-dev
      libglib2.0-dev
      libhiredis-dev
      libivykis-dev
      libjson0-dev
      libnet1-dev
      libriemann-client-dev
      libwrap0-dev
      pkg-config
      sqlite3
      xsltproc
      criterion-dev
      libmaxminddb-dev
      libxml2-utils
  - sudo pip install -r requirements.txt
before_script:
  - echo 'Europe/Budapest' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - ./autogen.sh
  - unset PYTHON_CFLAGS # HACK
  - if [ "$CC" = "gcc" ]; then
      EXTRA_WARN="--enable-extra-warnings";
    fi
  - if [ "$CC" = "clang" ]; then
      DISABLE_MONGODB="--disable-mongodb";
    fi
  - ./configure
      CFLAGS=-Werror
      --prefix=$HOME/install/syslog-ng
      --with-ivykis=internal
      --with-mongoc=internal
      --with-librabbitmq=internal
      --with-jsonc=system
      --disable-env-wrapper
      --disable-memtrace
      --enable-tcp-wrapper
      --enable-linux-caps
      --disable-sun-streams
      --enable-all-modules
      --disable-sql
      --enable-pacct
      --enable-manpages
      --with-python=2
      --with-docbook=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
      $EXTRA_WARN
      $DISABLE_MONGODB
script:
  - . tests/build-log-cflags-propagation.sh;
    if [ "$CC" = "gcc" ]; then
      export DISTCHECK_CONFIGURE_FLAGS="$CONFIGURE_FLAGS";
      exec_prop_check "make distcheck -j 3 V=1 --keep-going" ||
      {
        S=$?;
        make V=1 distcheck;
        find . -name test-suite.log |
        xargs cat;
        return $S;
      };
    else
      make --keep-going -j 3;
      S=$?;
      if [ "$S" = "0" ]; then
        make install
        . scripts/get-libjvm-path.sh || return $?;
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$JNI_LIBDIR";
        make func-test V=1;
      elif [ "$S" = "42" ]; then
        return $S;
      else
        make V=1 install;
        return $S;
      fi;
    fi
compiler:
  - gcc
  - clang

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    - env: B=style-check
      dist: trusty
      sudo: required
      install:
      - curl -4 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_14.04/Release.key | sudo apt-key add -
      - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_14.04 ./" | sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
      - sudo apt-get update -qq
      - sudo apt-get install -qq
          astyle
      before_script:
      - astyle --version
      script:
      - scripts/style-checker.sh format
      - git diff --exit-code
    - env: B=copyright-check
      sudo: false
      compiler: gcc
      install:
      before_script:
      script:
        - export COPYRIGHTVERBOSITY=1
        - tests/copyright/check.sh . .
    - env: B=trusty-cmake-internal
      compiler: gcc
      dist: trusty
      sudo: required
      before_script:
      git:
        submodules: true
      script:
        - mkdir build
        - cd build
        - cmake
            -DCMAKE_C_FLAGS=-Werror
            -DPYTHON_VERSION=2
            -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng
            ..
        - make --keep-going -j $(nproc) all test install
        - make VERBOSE=1 func-test
    - env: B=trusty-cmake
      compiler: clang
      dist: trusty
      sudo: required
      before_script:
      script:
        - mkdir build
        - cd build
        - cmake
            -DCMAKE_C_FLAGS=-Werror
            -DPYTHON_VERSION=2
            -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng
            ..
        - make --keep-going -j $(nproc) all test install
    - env: B=check
      os: osx
      osx_image: xcode8
      compiler: clang
      install:
        - brew update
        - brew install
            autoconf-archive
            binutils
            bison
            eventlog
            geoip
            geoipupdate
            glib
            gradle
            hiredis
            libdbi
            libnet
            riemann-client
        - geoipupdate
        - pip install -r requirements.txt
        - export PATH=/usr/local/opt/bison/bin:/usr/local/opt/libnet/bin:$PATH
        - export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:$PKG_CONFIG_PATH
      before_script:
        - ./autogen.sh
        - ./configure
            --disable-sun-streams
            --disable-systemd
            --disable-pacct
            --enable-all-modules
            --disable-smtp
        - make --keep-going -j 3 ||
          {
            S=$?;
            make V=1;
            return $S;
          }
      script:
        - make --keep-going check ||
          {
            S=$?;
            make V=1 check;
            find . -name test-suite.log |
            xargs cat;
            return $S;
          }

branches:
  except:
    - /wip/
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/1c6e3a6f10348748585a
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: true     # default: false
